
```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(feather)
library(lubridate)
library(usmap)
```

## county_features

```{r}
source("./county_features_cases.R")
```

```{r}
county_features %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day)) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")
```

```{r}
county_features %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome)) %>% 
  pull(days_btwn_stayhome_thresh) %>% summary
```

```{r}
county_map <- county_features %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "threshold_day") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```

```{r}
county_train <- county_features 

## Remove timestamps with negative counts
county_train <- county_train[-which(county_train$deaths < 0), ]

## Include only deaths up to May 21
county_train %<>% 
  filter(!is.na(threshold_day), 
         threshold_day <= as.Date("2020-05-21"),
         date <= as.Date("2020-05-21"))

## Require at least 15 days since threshold
remove_fips <- county_train %>% 
  group_by(fips) %>% 
  summarise(max_days = max(days_since_thresh)) %>% 
  filter(max_days < 15) %>% 
  pull(fips)

county_train <- county_train[!county_train$fips %in% remove_fips, ]
#length(unique(county_train$fips))

county_train %<>% 
  group_by(fips) %>% 
  arrange(date) %>% 
  mutate(index = row_number(), 
         index_desc = sort(index, decreasing = TRUE)) %>% 
  ungroup()

county_map <- county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "threshold_day") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```

```{r}
cum_cases_ <- county_train %>% 
  filter(index_desc == 1) %>% 
  pull(cum_cases)

summary(cum_cases_)
```

```{r}
## Make smaller dataset
county_map <- county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome)) %>% 
  mutate(train = cum_cases >= quantile(cum_cases_, 0.6))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "train") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_manual(values = c("red", "white"))
```

## county_train

```{r}
county_train <- read_feather("./county_train_cases.feather")
```

```{r}
county_train %>% 
  filter(index_desc == 1,) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")
```

```{r}
county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome)) %>% 
  pull(days_btwn_stayhome_thresh) %>% summary
```

```{r}
county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome), 
         days_btwn_stayhome_thresh > 0) %>% 
  pull(days_btwn_stayhome_thresh) %>% summary
```

```{r}
county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome)) %>% 
  pull(speed_btwn_stayhome_thresh) %>% summary
```

```{r}
county_map <- county_train %>% 
  filter(index_desc == 1, 
         !is.na(threshold_day), 
         !is.na(stayhome)) %>% 
  mutate(days_btwn_stayhome_thresh = -days_btwn_stayhome_thresh)

plot_usmap(data = county_map, include = county_map$fips, 
           values = "threshold_day") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```

```{r}
county_train %>% 
  filter(fips %in% c("48453", "06075")) %>% 
  ggplot() + 
  geom_point(aes(x=date, y=cases, color=fips)) + 
  geom_line(aes(x=date, y=roll_cases, color=fips))
```

## nchs

```{r}
nchs <- read_feather("./nchs.feather")
```

```{r}
# why are counties having an nchs of 1,2,3,4 not in county_train?
train_fips <- unique(county_train$fips)

nchs %>%
  filter(nchs %in% c(1,2,3,4), 
         !fips %in% train_fips) %>% 
  arrange(nchs)
```

```{r}
# counties with nchs in group 1 that are filtered in county_train
county_features %>% 
  filter(index_desc == 1, 
         fips %in% c("40109", "01007"))
#40109 oklahoma did not enact stayhome
#cum_deaths did not reach q60
```

```{r}
## comparing nchs population entry and county_desc pop variable
county_features %>% 
  filter(index_desc == 1) %>% 
  mutate(diff_pop = pop - popul) %>%
  ggplot() +
  geom_histogram(aes(x = diff_pop))
```

```{r}
## distribution of nchs in county_train
county_train %>% 
  filter(index_desc == 1) %>% 
  pull(nchs) %>% summary()
```

```{r}
## distribution of nchs and speed_btwn
tt <- county_train %>% 
  filter(index_desc == 1) %>%
  select(fips, nchs, speed_btwn_stayhome_thresh)

table(tt$nchs, tt$speed_btwn_stayhome_thresh)
```

```{r}
## distribution of population by nchs in train set
county_train %>% 
  filter(index_desc == 1) %>% 
  group_by(nchs) %>% 
  summarise(cum_cases_per_cap = mean(cum_cases_per_cap), 
            cum_deaths_per_cap = mean(cum_deaths_per_cap), 
            cum_cases_per_sq_mi = mean(cum_cases_per_sq_mi), 
            cum_deaths_per_sq_mi = mean(cum_deaths_per_sq_mi),
            pop = mean(pop), 
            popdensity = mean(popdensity))
```

```{r}
county_train %>% 
  group_by(nchs, fips) %>% 
  summarise(max_roll = max(roll_cases, na.rm = TRUE)) %>% 
  group_by(nchs) %>% 
  summarise(max_roll = mean(max_roll))
```

```{r}
county_map <- county_train %>% 
  filter(index_desc == 1)

plot_usmap(data = county_map, include = county_map$fips, 
           values = "nchs") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) 
```
