
```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(feather)
library(lubridate)
library(usmap)
library(viridis)
```

## county_desc

```{r}
county_desc <- read_feather("./county_desc.feather")
```

```{r}
summary(county_desc)
```

```{r}
county_desc %>% 
  select(fips, stayhome, gt50, gt500, schools, restaurants, entertainment) %>% 
  gather(key, value, -fips) %>% 
  filter(!is.na(value)) %>% 
  ggplot(aes(x = value, fill = key)) + 
  geom_bar() + 
  ggtitle("Intervention Dates")
```


```{r}
quantile(as.numeric(county_desc$gt50 - county_desc$gt500), c(0.15, 0.5, 0.85), na.rm = TRUE)
```

```{r}
quantile(as.numeric(county_desc$entertainment - county_desc$restaurants), c(0.15, 0.5, 0.85), na.rm = TRUE)
```

```{r}
quantile(as.numeric(county_desc$gt50 - county_desc$schools), c(0.15, 0.5, 0.85), na.rm = TRUE)
quantile(as.numeric(county_desc$restaurants - county_desc$schools), c(0.15, 0.5, 0.85), na.rm = TRUE)
```

```{r}
#stayhome, gt50, gt500, schools, restaurants, entertainment
quantile(as.numeric(county_desc$gt50 - county_desc$stayhome), c(0.15, 0.85), na.rm = TRUE)
quantile(as.numeric(county_desc$stayhome - county_desc$schools), c(0.15, 0.5, 0.85), na.rm = TRUE)
quantile(as.numeric(county_desc$restaurants - county_desc$stayhome), c(0.15, 0.85), na.rm = TRUE)
```

```{r}
county_desc %>% 
  select(fips, stayhome, gt50, gt500, schools, restaurants, entertainment) %>% 
  gather(key, value, -fips) %>% 
  group_by(key) %>% 
  summarize(no_intervention = sum(is.na(value)))
```

```{r}
county_map <- county_desc %>% 
  select(fips, stayhome) %>% 
  filter(!is.na(stayhome)) %>% 
  mutate(stayhome = strftime(stayhome, format = "%V"))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "stayhome") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_manual(values = c("green","yellow","red","black"))
```

```{r}
county_map <- county_desc %>% 
  select(fips, gt50) %>% 
  filter(!is.na(gt50)) %>% 
  mutate(gt50 = strftime(gt50, format = "%V"))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "gt50") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_manual(values = c("green","yellow","red","black"))
```

```{r}
county_map <- county_desc %>% 
  select(fips, schools) %>% 
  filter(!is.na(schools)) %>% 
  mutate(schools = strftime(schools, format = "%V"))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "schools") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_manual(values = c("green","yellow","red","black"))
```

```{r}
county_map <- county_desc %>% 
  select(fips, restaurants) %>% 
  filter(!is.na(restaurants)) %>% 
  mutate(restaurants = strftime(restaurants, format = "%V"))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "restaurants") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_manual(values = c("blue","green","yellow","red","black"))
```

## county_raw

```{r}
source("./county_raw.R")
```

```{r}
max(county_raw$date, na.rm = TRUE)
```

```{r}
# Counties with NA cases in county_counts. This might be because there are no cases or the county ID is not available in the raw data

county_map <- county_raw %>% 
  distinct(fips, county) %>% 
  mutate(no_counts = as.factor(!is.na(county)))

plot_usmap(data = county_map, values = "no_counts") +
  theme(legend.position = "right") + 
  scale_fill_manual(values=c("red", "white")) +
  theme(legend.title = element_blank())
```

## county_clean

```{r}
source("./county_clean.R")
```

```{r}
county_clean %>% 
  filter(index_desc == 1) %>% summary()
```

```{r}
county_map <- county_clean %>% 
  filter(index_desc == 1, 
         cum_cases_per_cap > 0) %>% 
  mutate(cum_cases_per_cap = log(cum_cases_per_cap))

plot_usmap(data = county_map,  
           include = county_map$fips, values = "cum_cases_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_viridis()
```

```{r}
county_map <- county_clean %>% 
  filter(index_desc == 1, 
         cum_deaths_per_cap > 0) %>% 
  mutate(cum_deaths_per_cap = log(cum_deaths_per_cap))

plot_usmap(data = county_map, 
           include = county_map$fips, values = "cum_deaths_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_viridis()
```

## county_features

```{r}
source("./county_features.R")
```

```{r}
county_map <- county_deaths_desc %>% 
  mutate(no_thresh = as.factor(is.na(threshold_day)))

plot_usmap(data = county_map, 
           include = county_map$fips, 
           values = "no_thresh") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_manual(values = c("white", "red"))
```

```{r}
county_cases_desc %>% 
  rename(threshold_cases = threshold_day) %>%
  select(fips, nchs, threshold_cases) %>% 
  left_join(county_deaths_desc %>% 
              rename(threshold_deaths = threshold_day) %>% 
              select(fips, nchs, threshold_deaths)) %>% 
  mutate(diff_thresh = as.numeric(threshold_deaths - threshold_cases)) %>% 
  ggplot() +
  geom_density(aes(x = diff_thresh, fill = nchs), alpha = 0.5)
```


```{r}
county_map <- county_cases_desc %>% 
  rename(threshold_cases = threshold_day) %>%
  select(fips, threshold_cases) %>% 
  left_join(county_deaths_desc %>% 
              rename(threshold_deaths = threshold_day) %>% 
              select(fips, threshold_deaths)) %>% 
  mutate(diff_thresh = as.numeric(threshold_deaths - threshold_cases))

plot_usmap(data = county_map, 
           include = county_map$fips, 
           values = "diff_thresh") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "red", midpoint = 10, high = "blue")
```

```{r}
county_cases_desc %>% 
  filter(!is.na(threshold_day)) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")

county_deaths_desc %>% 
  filter(!is.na(threshold_day)) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")
```

```{r}
county_cases_desc %>%
  mutate(days_btwn_stayhome_thresh = as.numeric(stayhome - threshold_day)) %>% 
  pull(days_btwn_stayhome_thresh) %>% summary 

county_deaths_desc %>% 
  pull(days_btwn_stayhome_thresh) %>% summary
```

```{r}
county_cases_desc %>%
  mutate(days_btwn_stayhome_thresh = as.numeric(stayhome - threshold_day)) %>% 
  ggplot() +
  geom_density(aes(x = days_btwn_stayhome_thresh, fill = nchs), alpha = 0.5)

county_deaths_desc %>% 
  ggplot() +
  geom_density(aes(x = days_btwn_stayhome_thresh, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>%
  mutate(days_btwn_stayhome_thresh = as.numeric(stayhome - threshold_day))
plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_stayhome_thresh") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")

plot_usmap(data = county_deaths_desc, include = county_deaths_desc$fips, 
           values = "days_btwn_stayhome_thresh") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")
```

```{r}
county_cases_desc %>%
  select(decrease_40_school_visits,
         decrease_40_recreation_visiting,
         decrease_40_total_visiting) %>% lapply(summary)
```

```{r}
county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day)) %>%
  pull(days_btwn_decrease) %>% summary

county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day)) %>%
  pull(days_btwn_decrease) %>% summary
```

```{r}
county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)

county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")

county_map <- county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_school_visits - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")
```

```{r}
county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_recreation_visiting - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)

county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_recreation_visiting - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_recreation_visiting - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")

county_map <- county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_recreation_visiting - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")
```

```{r}
county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_total_visiting - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)

county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_total_visiting - threshold_day)) %>%
  ggplot() +
  geom_density(aes(x = days_btwn_decrease, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_total_visiting - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")

county_map <- county_deaths_desc %>% 
  mutate(days_btwn_decrease = as.numeric(decrease_40_total_visiting - threshold_day))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "days_btwn_decrease") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 0, high = "red")
```

### safegr

```{r}
county_cases_desc %>% 
  mutate_at(vars(contains("baseline")), function(x){(1e4*x / .$pop) + 1e-6}) %>%
  select(baseline_school_visits,
         baseline_recreation_visiting,
         baseline_total_visiting) %>% lapply(summary)
```

```{r}
county_cases_desc %>% 
  mutate(baseline_per_cap = log((1e4 * baseline_school_visits / pop) + 1e-6)) %>%
  ggplot() +
  geom_density(aes(x = baseline_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(baseline_per_cap = log((1e4 * baseline_recreation_visiting / pop) + 1e-6)) %>%
  ggplot() +
  geom_density(aes(x = baseline_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(baseline_per_cap = log((1e4 * baseline_total_visiting / pop) + 1e-6)) %>%
  ggplot() +
  geom_density(aes(x = baseline_per_cap, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>% 
  mutate(baseline_per_cap = log((1e4 * baseline_school_visits / pop) + 1e-6))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "baseline_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 5, high = "red")

county_map <- county_cases_desc %>% 
  mutate(baseline_per_cap = log((1e4 * baseline_recreation_visiting / pop) + 1e-6))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "baseline_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 5, high = "red")
```

### nchs

```{r}
plot_usmap(data = county_cases_desc, include = county_map$fips, 
           values = "nchs") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_viridis(discrete = TRUE)
```

```{r}
county_cases_desc %>% 
  ggplot() +
  geom_density(aes(x = log(popdensity), fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  ggplot() +
  geom_density(aes(x = college, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  ggplot() +
  geom_density(aes(x = degree, fill = nchs), alpha = 0.5)

```

```{r}
plot_usmap(data = county_map, include = county_map$fips, 
           values = "college") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 30, high = "red")

plot_usmap(data = county_map, include = county_map$fips, 
           values = "degree") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 30, high = "red")
```


### cc

```{r}
county_cases_desc %>% 
  mutate(age_per_cap = log((1e4 * age_20_44 / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = age_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(age_per_cap = log((1e4 * age_45_64 / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = age_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(age_per_cap = log((1e4 * age_65_plus / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = age_per_cap, fill = nchs), alpha = 0.5)
```

```{r}
county_map <- county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * white / pop) + 1e-6) )

plot_usmap(data = county_map, include = county_map$fips, 
           values = "ethnic_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 8, high = "red")

county_map <- county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * black / pop) + 1e-6) )

plot_usmap(data = county_map, include = county_map$fips, 
           values = "ethnic_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 8, high = "red")

county_map <- county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * hispanic / pop) + 1e-6) )

plot_usmap(data = county_map, include = county_map$fips, 
           values = "ethnic_per_cap") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(low = "blue", midpoint = 8, high = "red")
```

```{r}
county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * white / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = ethnic_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * black / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = ethnic_per_cap, fill = nchs), alpha = 0.5)

county_cases_desc %>% 
  mutate(ethnic_per_cap = log((1e4 * hispanic / pop) + 1e-6) ) %>% 
  ggplot() +
  geom_density(aes(x = ethnic_per_cap, fill = nchs), alpha = 0.5)
```

## county_train

```{r}
county_train_cases <- read_feather("./county_train_cases.feather")
county_train <- read_feather("./county_train.feather")
```

```{r}
county_train_cases %>% 
  filter(fips %in% c("48453", "06075")) %>% 
  ggplot() + 
  geom_point(aes(x=date, y=cases, color=fips)) + 
  geom_line(aes(x=date, y=roll_cases, color=fips))

county_train %>% 
  filter(fips %in% c("48453", "06075")) %>% 
  ggplot() + 
  geom_point(aes(x=date, y=deaths, color=fips)) + 
  geom_line(aes(x=date, y=roll_deaths, color=fips))
```

```{r}
# Number of timestamps per days since thresholds without intervention
county_train_cases %>%
  filter(intervention == 0) %>%
  ggplot(aes(x = days_since_thresh)) +
  geom_bar()

county_train %>%
  filter(intervention == 0) %>%
  ggplot(aes(x = days_since_thresh)) +
  geom_bar()
```

```{r}
county_train_cases %>% 
  filter(index_desc == 1,) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")

county_train %>% 
  filter(index_desc == 1,) %>% 
  mutate(week_num = as.numeric(strftime(threshold_day, format = "%V")), 
         week_num = if_else(week_num < 11, 0, week_num), 
         week_num = if_else(week_num > 15, 0, week_num), 
         week_num = as.factor(week_num)) %>%
  ggplot(aes(x = threshold_day, fill = week_num)) + 
  geom_bar() +
  scale_fill_manual(values = c("grey", "blue", "green", 
                               "yellow", "red", "black")) + 
  labs(title = "Counties threshold day")
```

```{r}
summary(county_train_cases$days_btwn_decrease_thresh)
summary(county_train$days_btwn_stayhome_thresh)
```

```{r}
county_map <- county_train_cases %>% 
  filter(index_desc == 1) %>% 
  mutate(threshold_day = threshold_day - as.Date("2020-02-15"), 
         threshold_day = as.numeric(threshold_day))
plot_usmap(data = county_map, include = county_map$fips, 
           values = "threshold_day") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_gradient2(midpoint = 30)

county_map <- county_train %>% 
  filter(index_desc == 1) %>% 
  mutate(threshold_day = threshold_day - as.Date("2020-02-15"), 
         threshold_day = as.numeric(threshold_day))
plot_usmap(data = county_map, include = county_map$fips, 
           values = "threshold_day") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) +
  scale_fill_gradient2(midpoint = 40)
```

```{r}
## distribution of nchs in county_train
county_train_cases %>% 
  filter(index_desc == 1) %>% 
  pull(nchs) %>% summary()

county_train %>% 
  filter(index_desc == 1) %>% 
  pull(nchs) %>% summary()
```

## nchs

```{r}
nchs <- read_feather("./nchs.feather")
```

```{r}
summary(nchs)
```

```{r}
#counties with no population
nchs[is.na(nchs$popul), ]
```

```{r}
# why are counties having an nchs of 1,2,3,4 not in county_train?
train_fips <- unique(county_train$fips)

nchs %>%
  filter(nchs %in% c(1,2), 
         !fips %in% train_fips) %>% 
  arrange(nchs)
```

```{r}
# counties with nchs in group 1 that are filtered in county_train
county_features %>% 
  filter(index_desc == 1, 
         fips %in% c("40109", "51710"))
#40109 oklahoma did not enact stayhome
#51710 virginia cum_deaths did not reach q60
```

```{r}
## comparing nchs population entry and county_desc pop variable
county_train %>% 
  filter(index_desc == 1) %>% 
  mutate(diff_pop = pop - popul) %>%
  ggplot() +
  geom_histogram(aes(x = diff_pop))
```
