```{r, include=FALSE}
library(tidyverse)
library(magrittr)
library(feather)
library(lubridate)
library(usmap)
library(viridis)
```

```{r}
safegr <- read_feather("./safegr.feather")
```

```{r}
safegr %>% 
  filter(!key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_40, fill = key)) + 
  geom_bar()
```

```{r}
safegr %>% 
  filter(key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_40, fill = key)) + 
  geom_bar()
```

```{r}
safegr %>% 
  filter(!key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_50, fill = key)) + 
  geom_bar() + 
  theme(legend.title = element_blank()) +
  xlab("50% decrease in visits")
```

```{r}
safegr %>% 
  filter(key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_50, fill = key)) + 
  geom_bar() + 
  theme(legend.title = element_blank()) +
  xlab("50% decrease in visits")
```

```{r}
safegr %>% 
  filter(!key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_70, fill = key)) + 
  geom_bar() + 
  theme(legend.title = element_blank()) +
  xlab("70% decrease in visits")
```

```{r}
safegr %>% 
  filter(key %in% c("total_visiting", "hometime_sd")) %>% 
  ggplot(aes(x = decrease_70, fill = key)) + 
  geom_bar() + 
  theme(legend.title = element_blank()) +
  xlab("70% decrease in visits")
```

```{r}
xx <- safegr %>% 
  filter(key == "total_visiting") %>% 
  rename(decrease = decrease_70) %>% 
  select(fips, key, decrease)

yy <- safegr %>% 
  filter(key == "hometime_sd") %>% 
  rename(decrease = decrease_40) %>% 
  select(fips, key, decrease)

rbind(xx, yy) %>% 
  ggplot(aes(x = decrease, fill = key)) + 
  geom_bar() + 
  theme(legend.title = element_blank()) +
  xlab("70% decrease in total visits \n 30% increase in median time spent at home")
```

```{r}
county_map <- safegr %>% 
  filter(key == "school_visits") %>% 
  mutate(decrease_40 = decrease_40 - as.Date("2020-02-15"), 
         decrease_40 = as.numeric(decrease_40))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "decrease_40") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(midpoint = 30)
```

```{r}
county_map <- safegr %>% 
  filter(key == "college_visits") %>% 
  mutate(decrease_40 = decrease_40 - as.Date("2020-02-15"), 
         decrease_40 = as.numeric(decrease_40))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "decrease_40") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(midpoint = 30)
```

```{r}
county_map <- safegr %>% 
  filter(key == "recreation_visiting") %>% 
  mutate(decrease_40 = decrease_40 - as.Date("2020-02-15"), 
         decrease_40 = as.numeric(decrease_40))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "decrease_40") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(midpoint = 30)
```

```{r}
county_map <- safegr %>% 
  filter(key == "total_visiting") %>% 
  mutate(decrease_40 = decrease_40 - as.Date("2020-02-15"), 
         decrease_40 = as.numeric(decrease_40))

plot_usmap(data = county_map, include = county_map$fips, 
           values = "decrease_40") +
  theme(legend.position = "right") + 
  theme(legend.title = element_blank()) + 
  scale_fill_gradient2(midpoint = 30)
```

```{r}
## Join interventions and safegr data
county_desc <- read_feather("./county_desc.feather")
safegr_melt <- safegr %>% 
  pivot_wider(names_from = key, values_from = -c(fips, key)) %>% 
  left_join(county_desc)
```

```{r}
safegr_melt %<>% 
  mutate(days_betw_schools_decrease = 
           as.numeric(decrease_70_school_visits - schools), 
         days_betw_restaurants_decrease = 
           as.numeric(decrease_50_recreation_visiting - restaurants), 
         days_betw_stayhome_decrease = 
           as.numeric(decrease_70_total_visiting - stayhome))
summary(safegr_melt$days_betw_schools_decrease)
summary(safegr_melt$days_betw_restaurants_decrease)
summary(safegr_melt$days_betw_stayhome_decrease)
````
